- components/issue-list-item.tsx
- components/loading.tsx
- components/oracle.tsx
- components/page-hero.tsx
- contexts/application.tsx
- contexts/reducers/change-load-state.ts
- interfaces/issue-data.ts
- pages/_app.tsx
- pages/account/index.tsx
- pages/council.tsx
- pages/developers.tsx
- pages/issue.tsx
- pages/style-guide.tsx
- pages/styles.tsx
- services/github-microservice.ts
change how we decide if loading is still active by adding weight
> change where Loading component lives so it can infer the correct state

- components/main-nav.tsx
> Same page structure

- components/account-hero.tsx
- components/main-nav.tsx
- components/oracles-actions.tsx
- components/oracles-delegate.tsx
- components/oracles-take-back.tsx
- contexts/application.tsx
- contexts/reducers/change-balance.ts
- contexts/reducers/index.ts
- interfaces/application-state.ts
- interfaces/balance-state.ts
- interfaces/enums/reduce-action-names.ts
> hotfix locks and oracles

- components/create-proposal.tsx
- components/network-tx-button.tsx
- components/toaster.tsx
- contexts/application.tsx
- contexts/reducers/add-toast.ts
- contexts/reducers/index.ts
- contexts/reducers/remove-toast.ts
- interfaces/application-state.ts
- interfaces/enums/reduce-action-names.ts
- interfaces/toast-notification.ts
- package-lock.json
- package.json
introduce <Toaster /> component and state changers
---
https://app.clubhouse.io/bepro/story/263/shouldn-t-show-the-validators-action-create-proposal-if-the-address-does-not-have-above-25m-bepro
https://app.clubhouse.io/bepro/story/262/should-display-the-error-messages-on-transaction-fails-on-the-webapp-and-success-if-it-succeeds
> hide create proposal button if < COUNCIL_AMOUNT

- components/avatar.tsx
- components/create-proposal-distribution-item.tsx
- components/issue-hero.tsx
> Feature/avatar GitHub handle issue page

- interfaces/issue-data.ts
- pages/council.tsx
- pages/oracle/new-issues.tsx
- pages/oracle/ready-to-merge.tsx
- services/github-microservice.ts
- fix query params to filter state
- create interface to `Issue State`
> fix: filter state issues

- pages/account/index.tsx
- services/github-microservice.ts
- list my issues by ghlogin
[BE PR](https://github.com/bepronetwork/microservice-github/pull/21)
> feat: list my issues by ghlogin

- components/page-actions.tsx
- pages/account/index.tsx
- services/github-microservice.ts
- Update issue state when redeem
[BE PR](https://github.com/bepronetwork/microservice-github/pull/24)
> feat: update issue state

- contexts/application.tsx
- pages/parity.tsx
- services/bepro-service.ts
- services/github-microservice.ts
> copy comments and fix error on trying to join a non existant user to an existance handle and address

- components/nation-dialog.tsx
- services/github-microservice.ts
[PR BE](https://github.com/bepronetwork/microservice-github/pull/33)
> feat: fix country tag

- components/issue-hero.tsx
- components/issue-list-item.tsx
- interfaces/issue-data.ts
- package.json
[BE](https://github.com/bepronetwork/microservice-github/pull/47)
> feat: refactor repository

- components/create-proposal.tsx
- components/issue-proposals.tsx
- components/modal.tsx
- components/network-tx-button.tsx
- components/oracles-actions.tsx
- components/oracles-take-back-item.tsx
- components/page-actions.tsx
- components/proposal-item.tsx
- components/proposal-progress-bar.tsx
- components/transaction-modal.tsx
- components/transactions-list.tsx
- contexts/application.tsx
- pages/api/issue/index.ts
- pages/api/past-events/close-issue/index.ts
- pages/api/past-events/index.ts
- pages/api/past-events/move-to-open/index.ts
- pages/api/past-events/redeem-issue/index.ts
- pages/api/pull-request/index.ts
- pages/create-issue.tsx
- pages/issue.tsx
- pages/proposal.tsx
- services/bepro-service.ts
- styles/styles.scss
- x-hooks/use-api.tsx
- x-hooks/use-filters.tsx
- x-hooks/use-pending-issue.tsx
- x-hooks/useTransactions.ts
- button action on proposal item matches design
- show modal to council when looking at a proposal that can't be merged
- formatting amounts in case of a wild .999
- fix pr id not showing on page
- slow get receipt logic to match metamask speed
> 202111161646

- components/not-mergeable-modal.tsx
- components/oracles-delegate.tsx
- components/page-actions.tsx
- interfaces/issue-data.ts
- pages/api/issues/index.ts
- pages/api/pull-request/index.ts
- pages/proposal.tsx
- validating delegateTo and currentAddress
- hide modal if already exists a merged PR
- fix PR number and author name
> 202111231709

- components/page-actions.tsx
> adjusting size of "merge" button

- components/comment.tsx
- components/issue-proposal-progress-bar.tsx
- components/oracles-actions.tsx
- components/oracles-take-back-item.tsx
- public/locales/en/common.json
- public/locales/pt/common.json
- styles/fonts.scss
- styles/styles.scss
- styles/x-pagination.scss
- styles/x-popover.scss
- Adjusting fonts
- Adjusting texts
- Adjusting progress bountie
> UI bugs fixes 

- components/connect-wallet-button.tsx
- components/wrong-network-modal.tsx
- helpers/networks.ts
- public/locales/en/common.json
Created error logic and some checks to avoid situations where the button is clicked but nothing happens
> Dev 301 wrong network modal add network modal

- .env.example
- components/change-token-modal.tsx
- components/connect-wallet-button.tsx
- components/custom-network/token-configuration.tsx
- components/deploy-nft-modal.tsx
- components/network-list-item.tsx
- components/networks-list.tsx
- components/not-listed-tokens.tsx
- components/oracle.tsx
- components/oracles-actions.tsx
- components/page-hero.tsx
- components/price-conversor-modal.tsx
- interfaces/token.ts
- next.config.js
- pages/[network]/birds-eye.tsx
- pages/[network]/council.tsx
- pages/[network]/developers.tsx
- pages/networks.tsx
- public/locales/en/custom-network.json
- services/bepro-service.ts
- services/coingecko.ts
- x-hooks/use-api.tsx
environment variable created to manage the default currency of web-app
NEXT_PUBLIC_CURRENCY_MAIN
> Vhc 311 total settler conversion

- contexts/network-settings.tsx
- next.config.js
- pages/[network]/proposal.tsx
- pages/api/_middleware.ts
- pages/api/nft/index.ts
- pages/api/search/issues/index.ts
- pages/api/seo/[...ids].ts
- services/dao-service.ts
- services/ipfs-service.ts
- x-hooks/use-api.tsx
- x-hooks/use-bepro.tsx
* DEV-872 fix seo url
* DEV-872 hotfix search issue
* DEV-872 hotfix isCouncil condition
* DEV-872 create NFT uri to close bounty
* DEV-872 add participants to nft
* DEV-872 fix requests changes
* DEV-872 fix labels
> Dev 872 add nft uri to the close bounty action (#598)

- components/create-pull-request-modal.tsx
- contexts/reducers/change-spinners.ts
- helpers/formatNumber.ts
- public/locales/en/common.json
- public/locales/pt/common.json
- x-hooks/use-repos.ts
adds forms.required and adds it to the PR modal
> dev-895 Description is a required field on the create pull request modal, but it is not indicated

- components/council-layout.tsx
- components/custom-network/amount-card.tsx
- components/loading.tsx
- components/network-tx-button.tsx
- components/networks-list.tsx
- components/oracles-actions.tsx
- components/oracles-delegate.tsx
- components/page-actions.tsx
- components/page-hero.tsx
- components/profile/my-network-settings.tsx
- components/update-bounty-amount-modal.tsx
- contexts/bounty-effects.tsx
- contexts/global-effects.tsx
- helpers/formatNumber.ts
- pages/[network]/bounty.tsx
- pages/[network]/developers.tsx
- pages/[network]/profile/bepro-votes.tsx
- pages/[network]/proposal.tsx
- pages/[network]/pull-request.tsx
- public/locales/en/common.json
- public/locales/pt/common.json
- x-hooks/use-authentication.tsx
- x-hooks/use-bepro.tsx
- x-hooks/use-bounty.tsx
- x-hooks/use-dao.tsx
- x-hooks/use-network.tsx
changes amount to be formated to T if bigger than 18 numbers, not accounting with decimals
> dev-1012 Ethereum integer limit breaks UI

- components/issue-list-item.tsx
Reverts bepronetwork/web-network#745
> Revert "DEV 1170 switch date format on bounty-list to "X time ago""

- components/profile/my-network-settings/tokens-settings.tsx
fix request -
As we only need to know the lowest block, maybe we can use a `reduce` on the `Promise.all` result to get it
_Originally posted by @vhcsilva in https://github.com/bepronetwork/web-network/pull/778#discussion_r1055615900_
> improve read code tokens settings

- components/nav-avatar.tsx
Old   ---------------------------------------------------------------------                                                                                                                        New
> BEPRO 1500 GitHub name breaking layout
